### ISSUE TITLE
One of jacobian LEMtoC or LEMtoU is broken

### ISSUE THREAD

**Issue by krigga** [iden3/wasmcurves#49]
`ffjavascript` converts its coordinates to affine before calling both of these functions https://github.com/iden3/ffjavascript/blob/5b395a33bb1b61eff8990826134169aa6d445726/src/wasm_curve.js#L220-L230 and https://github.com/iden3/ffjavascript/blob/5b395a33bb1b61eff8990826134169aa6d445726/src/wasm_curve.js#L239-L249
Then this library calls the affine variants of functions in the LEMtoU case (seemingly the correct one) 
https://github.com/iden3/wasmcurves/blob/2e86c0e65e0d5f7abadda9472256ea766e56c5eb/src/build_curve_jacobian_a0.js#L1215-L1228
but calls non-affine variants of functions in the LEMtoC case (seemingly incorrect)
https://github.com/iden3/wasmcurves/blob/2e86c0e65e0d5f7abadda9472256ea766e56c5eb/src/build_curve_jacobian_a0.js#L1173-L1200
In my testing this led to the point at infinity not having the 0x40 flag set in the first byte when being serialized to the compressed variant.
A similar discrepancy seems to exist with the UtoLEM and CtoLEM functions

**Comment by krigga** [comment]
Correction: I got confused and the bug seems to only exist in LEMtoC - it expects affine coordinates, but checks them to be zero using the non-affine isZero rather than the isZeroAffine variant, hence why 0x40 is not set for the point at infinity in compressed form. Everything else seems to be fine.

**Comment by phated** [comment]
Do you want to submit a PR that I can assign others to review?

**Comment by krigga** [comment]
@phated I created a PR that should fix this issue https://github.com/iden3/wasmcurves/pull/52
